name: application
version: 1
summary: Qt Application Example
description: A simple text editor
confinement: devmode

apps:
  application:
    command: desktop-launch application
    plugs: [unity7, home]

parts:
  application:
    source: src/
    plugin: qmake
    qt-version: qt6
    after: [qt6]
  qt6:
    source: .
    plugin: make
    make-parameters: ["SRC_DIR=../src"]
    build-packages:
      - qt6-base-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt6gui6
      - libgdk-pixbuf2.0-0
      - libqt6svg6 # for loading icon themes which are svg
      - appmenu-qt5

