name: rpi-imager
base: core22
adopt-info: imagewriter
summary: Raspberry Pi Imager
website: https://www.raspberrypi.com/software/
source-code: https://github.com/raspberrypi/rpi-imager
issues: https://github.com/waveform80/imager-snap
icon: images/rpi-imager.png
license: Apache-2.0
description: |
  Raspberry Pi Imager is an easy to use application for installing Raspberry Pi
  OS, or other operating systems, to an SD card ready to use with your
  Raspberry Pi.

  Usage is as simple as:

  1. Pick the Raspberry Pi board you want to use.

  2. Pick the operating system you want to write.

  3. Pick the storage you want to write it to (SD card, hard drive, SSD, etc.)

  4. Click "NEXT", confirm you wish to overwrite your storage and wait!

  The application also verifies that the operating system has been written
  correctly after writing has finished. With certain operating system images,
  the imager also supports customizing the first boot configuration (you will
  be prompted for more information after selecting "NEXT" in this case).
compression: lzo
grade: stable
confinement: strict

apps:
  rpi-imager:
    command: usr/local/bin/rpi-imager
    desktop: usr/local/share/applications/rpi-imager.desktop
    extensions:
      - kde-neon
    environment:
      DISABLE_WAYLAND: 1
      # Use GTK3 cursor theme, icon theme and open/save file dialogs
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - x11
      - opengl
      - network
      - desktop
      - desktop-legacy
      - home
      - removable-media  # required to re-write first-boot configuration
      - mount-observe    # required to report mounts on target media
      - network-manager  # required to grab image
      - network-control
      - cifs-mount
      - udisks2          # required for writing to sd card
      - hardware-observe # required to find card with lsblk
      - wayland          # required for theming on wayland
      - gsettings        # required for theming on wayland

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  imagewriter:
    plugin: cmake
    cmake-parameters:
      - -DENABLE_CHECK_VERSION=OFF
    source: https://github.com/raspberrypi/rpi-imager.git
    source-subdir: src
    source-type: git
    override-pull: |
      craftctl default
      last_committed_tag="$(git describe --tags $(git rev-list --tags --max-count=1))"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//' )"
      git fetch
      git checkout "$last_committed_tag"
      echo "Building $last_committed_tag_ver"
      craftctl set version="$last_committed_tag_ver"
      # Strip out the vendored dependencies and embedded source
      if [ -d "$CRAFT_PART_SRC"/embedded ]; then
        rm -fr "$CRAFT_PART_SRC"/embedded
      fi
      if [ -d "$CRAFT_PART_SRC"/src/dependencies ]; then
        pushd "$CRAFT_PART_SRC"/src/dependencies
        rm -rf cmcurl cmliblzma fat32format libarchive-* zlib-* zstd-*
        popd
      fi
      # Point the icon to the right place
      sed -i -e \
        's|^Icon=rpi-imager|Icon=/usr/local/share/icons/hicolor/128x128/apps/rpi-imager.png|' \
        "$CRAFT_PART_SRC"/src/linux/rpi-imager.desktop
    stage-packages:
      - dosfstools
      - fdisk
      - libarchive13
      - libcurl3-gnutls
    build-snaps:
      - kf5-5-111-qt-5-15-11-core22
      - kf5-5-111-qt-5-15-11-core22-sdk
    build-packages:
      - cmake
      - libarchive-dev
      - zlib1g-dev
      - liblzma-dev
      - libcurl4-gnutls-dev
      - libgnutls28-dev
      - libdrm-dev
      - pkg-config
      - libgles-dev
    prime:
      - -usr/lib/aarch64-linux-gnu/libicuio.so.70.1
      - -usr/lib/aarch64-linux-gnu/libicutest.so.70.1
      - -usr/lib/aarch64-linux-gnu/libicutu.so.70.1
      - -usr/lib/aarch64-linux-gnu/libicui18n.so.70.1
